### ISSUE TITLE
TypeError: tags.map is not a function

### ISSUE THREAD

**Issue by heyakyra** [elm-land/elm-land#35]
I'm having a strange issue that does not seem to be due to a code change (because I hadn't updated `elm-land` and upgrading/downgrading makes no difference), so perhaps it is an issue with nodejs or something else on my system.

```bash
elm-land server
TypeError: tags.map is not a function
    at toSelfClosingHtmlTags (/var/home/kyra/.local/lib/node_modules/elm-land/src/effects.js:322:17)
    at generateHtml (/var/home/kyra/.local/lib/node_modules/elm-land/src/effects.js:333:18)
    at Object.run (/var/home/kyra/.local/lib/node_modules/elm-land/src/effects.js:377:28)
    at main (/var/home/kyra/.local/lib/node_modules/elm-land/src/index.js:11:30)
```

I'm running 
```bash
node --version
v16.15.1
```

And my operating system is Fedora 36

**Comment by heyakyra** [comment]
Nevermind, this was due to a bad change I made:
```
-      "link": []
+      "link": { "rel": "stylesheet", "href": "/styles.css" }
```

which should have been
```
-      "link": []
+      "link": [{ "rel": "stylesheet", "href": "/styles.css" }]
```
